In [17]:
import cvxpy as cp
import numpy as np
from Hoffman import hoffman

## Example 1: box

$$
A = \begin{pmatrix}
I_n \\ -I_n
\end{pmatrix}
$$

In [18]:
n = 4
A = np.vstack([np.eye(n),-np.eye(n)])
H, FF, II, iternumber = hoffman(A,1000)
print("H(A) =",H)

H(A) = 4.0


## Example 2: simplex


$$
A = \begin{pmatrix}
I_n \\ -1^T
\end{pmatrix}
$$


In [19]:
n = 6
A = np.vstack([np.eye(n),-np.ones(n)])
H, FF, II, iternumber = hoffman(A,1000)
print("H(A) =",H)

H(A) = 11.0


## Example 3:  $\; \ell_1$ unit ball

$$
A = \begin{pmatrix}
-1 & -1 & \cdots & -1 \\ 
-1 & -1 & \cdots & 1 \\
\vdots & \vdots & \ddots & \vdots\\
1 & 1 & \cdots & 1 
\end{pmatrix}
$$

In [20]:
n = 3
A = -np.ones((4,2))
A[1,1] = 1
A[2,0] = 1
A[3,:] = 1
ni = 4
# construct A recursively
for i in range(n-2):
    A1 = np.hstack([-np.ones((ni,1)),A])
    A2 = np.hstack([np.ones((ni,1)),A])
    A = np.vstack([A1,A2])
    ni = 2*ni
print("A=\n",A) 

A=
 [[-1. -1. -1.]
 [-1. -1.  1.]
 [-1.  1. -1.]
 [-1.  1.  1.]
 [ 1. -1. -1.]
 [ 1. -1.  1.]
 [ 1.  1. -1.]
 [ 1.  1.  1.]]


In [21]:
H, FF, II, iternumber = hoffman(A,5000)
print("H(A) =",H)

H(A) = 3.0
